### ISSUE TITLE
Is a tabular formatted output useful for scientists?

### ISSUE THREAD

**Issue by MKLau** [End-to-end-provenance/dev#109]
From Emery on uesday, June 06, 2017 9:41 AM via end2endprov@googlegroups.com

After our meeting yesterday, Aaron offered an interesting analogy from the art world, where provenance has real value:  A casual art-lover may readily accept a painting as genuine if it’s signed or if an art dealer vouches for it, while a museum contemplating a major purchase may want to examine every brush stroke under a microscope.  The tools used to establish authenticity will vary depending on the context and the amount of money involved.
 
With this in mind we might consider developing and promoting RDataTracker as an all-purpose provenance tool.  For the scientist, it could provide a table of useful information, e.g. script name, input & output files, execution time, software versions, and other environmental details (perhaps as a CSV file).  For script debugging or data forensics, it could provide a full-fledged provenance graph (the DDG).  Since we already generate the latter, it shouldn’t be too hard to generate the former.
 
We might even promote the tabular output as the default, as a way of getting scientists to use our tools, since there should be little or no impact on performance.  If scientists find RDT useful for tracking basic information about the execution of a script, they may begin to explore its use for script debugging, etc.

**Comment by MKLau** [comment]
From Emery on uesday, June 11, 2017 9:41 AM via end2endprov@googlegroups.com

Following up on this line of thought:
 
In addition to a table of environmental information (hardware, software, etc), RDataTracker might provide a table of data objects created by a script.  Attached is a first draft of such a table for the met-real-time.R script using the default level of detail and columns as follows:
 
     NUMBER = sequential number (also data node number in the DDG)
     NAME = name of variable
     VALUE = value of variable or path to snapshot file
     SCOPE = scope of variable (simplified to: global, local, undefined)
     CREATED = line of code where variable was created
     USED = line(s) of code (if any) where variable was used
     FILE = name of file read or written by script
     HASH = MD5 hash of file
 
This might be the “long form” of the table.  We could also return a “short form” that has only inputs and outputs.  In either case we should be able to capture dynamic inputs (e.g. random numbers, user input, web downloads, etc)  that may not be captured by other tools but are essential for reproducibility.
 
Ecologists are accustomed to working with tables but we could also provide tools for sorting, subsetting, querying, etc.
 
Would scientists find this useful?

**Comment by MKLau** [comment]
From Margo Selzter on Jun 12 via end2endprov@googlegroups.com

Should we be making this an issue on github so we can track it better?

**Comment by blernermhc** [comment]
I think there are 2 questions here:  what information do we collect, and what do we present to the users.  It could be that we need to collect detailed information in order to answer higher-level questions, unless we have a very limited set of questions that we support.

In general, I think it would be very unusual for a user to want to see tables about their data.  A more interesting question, in my mind, is what questions could we answer if we had data tables rather than full ddgs and what questions could we answer with full ddgs but not data tables.

I think most of the questions in Margo's response above require more than just data tables.

Then, how do we allow a scientist to ask interesting questions without learning a query language and without needing to do a lot of ddg examination themselves?

**Comment by erboose** [comment]
My guess is that we’ll want to collect detailed information (at least level 0) in any case, even if the user does not wish to view the DDG.  If we do that we’ll be in a better position to answer questions like Margo’s and there will still be an option to view the entire DDG later, if desired.

I could see roles for both query support and tables of information.  Queries are good if you know what question to ask.  But scientists often want to look at their data and are accustomed to working with tables.  Perhaps we can interest them in looking at their provenance data.  For example, the data table can be sorted by name to see all instances of a variable in the script execution.  And a modified procedure table could be sorted by execution time to see which steps took the longest to execute.  And if we add the edges table (admittedly not very user friendly), that’s the entire graph in three tables.

**Comment by erboose** [comment]
Experimenting with other ways of looking at the DDG.  Here's a text version from Matt's sensitivity.R script (detail level = 1), showing the operational steps in the order executed, the corresponding line number in square brackets (1:7 means line 7 in the 1st sourced script), and data inputs and outputs for each step.  This version was created after script execution from the node and edge tables saved when save.debug=TRUE in ddg.run.
[sensitivity-ddg-text.txt](https://github.com/End-to-end-provenance/dev/files/1072850/sensitivity-ddg-text.txt)

**Comment by tfjmp** [comment]
Looking at the examples here:
```
foodWeight <- c(rep(0, n1), rep(fw, n2), rep(0, n3))
     Input:  n1 = 3
     Input:  fw = 54.5
     Input:  n2 = 5
     Input:  n3 = 2
     Output:  foodWeight = 27-foodWeight.csv
```

How is that different that what I could get from running my code in the debugger? I am not familiar with R debugger, but examining variables values is a pretty standard feature. What is the added value here?

```
51  [12]  mineralization
     Input:  mineralization = #ddg.function
     Input:  x = 0
     Input:  w = 0
     Input:  c = 1

52  [1:12]  (w * x)/c
     Input:  w = 0
     Input:  x = 0
     Input:  c = 1
     Output:  mineralization(x[length(minute)-1],w[length(minute)],c) return = 0
```
This appears slightly off to me (although I did not see the original code).

I can understand also why we want to collect less data, but it does not to appear to be the case here, we seem to be collecting more or less the same amount of details in a non standard format. I would rather see us collecting the minimum and sufficient information to upload to dataverse as ProvJSON rather than generating an output that is not compatible with anything. It seems to me this is going backward in regards of the improvement we made this year.

**Comment by erboose** [comment]
The current file outputs from RDT (ddg.txt, ddg.json) are in exchange formats that are not intended to be read by humans (except perhaps for occasional spot checking).  What I was looking for here was a text format (with all the original detail) that would be more readable for folks who prefer a text / command line approach to a visual / graphics approach.

So, for example, we might create a tool that provides the above snippet in response to the query "what happened in line 19?" (or perhaps several such snippets, if the line executed more than once).  Or perhaps someone accustomed to working with text files would use the entire file to check on intermediate values at various points in the execution.

I agree that we also need to find ways to distill the information we collect.  But that's a somewhat different problem.  And I would guess it's more a question of distilling than of collecting less information.

**Comment by margoseltzer** [comment]
Perhaps we should do some research and write  a short summary about what tools/techniques/presentations others have come up with for presenting provenance in a useful manner? We can’t possibly be the first to have wrestled with this problem.

I did some quick googling and came up with the following few papers that looked kind of interesting:

PROX: Approximated Summarization of Data Provenance
Characterizing Provenance in Visualization and Data Analysis: An Organizational Framework of Provenance Types and Purposes.
On Presenting Apropos Provenance for Situation Awareness and Data Forensics

**Comment by tfjmp** [comment]
> So, for example, we might create a tool that provides the above snippet in response to the query "what happened in line 19?" (or perhaps several such snippets, if the line executed more than once). Or perhaps someone accustomed to working with text files would use the entire file to check on intermediate values at various points in the execution.

Back to my first message, what are we adding here that we could not obtain from the R debugger?  Or more fundamentally what is the problem that this feature is trying to solve? Provenance purpose is to look at an historical record of events, if I want to check the value at a time t in my script, the standard debugger do it perfectly no? I just need to halt my script execution at that point and examine the variable. Is that not possible in R?

**Comment by blernermhc** [comment]
The difference from debugging is that with debugging you need the 
foresight that you are going to want to look at the values at a 
particular point in the code before you execute the code.   With 
provenance, you don't need to decide what you want to look at until 
after you have executed the code.

**Comment by erboose** [comment]
Right.  A debugger allows us to check values at run time, but we also want to be able to check values after execution.  If we run the script again we might get different values.

We can already do this, of course, with DDG Explorer.  What I was looking into here was alternatives to the visual representation.

**Comment by erboose** [comment]
[met-real-time-ddg-short.txt](https://github.com/End-to-end-provenance/dev/files/1075341/met-real-time-ddg-short.txt)
How about something like this as a (quick & dirty) example of a distilled DDG that captures only critical inputs & outputs.  The example contains line number, variable name, file name (for snapshots) or file name plus hash value (for files read or written by the script).  This example includes a web download but the process could be extended to capture other dynamic inputs (random number seeds, keyboard input, etc).  Combined with the original script(s) this should provide true reproducibility.

As an aside, we might want to capture the entire contents of critical inputs and outputs by default, even if max.snapshot.size has been set to less than complete.

**Comment by MKLau** [comment]
I like Margo's suggestion of tracking down papers/projects that are also doing provenance analysis. I'll open up a channel on Slack for us to collate and discuss this topic. I'll drop the PDFs into the channel too. I did a quick scan of these papers that Margo found, and the Ragan paper presents a great review of this area and a framework thinking about it. It does, however, largely focus on visuals tools, and after a brief discussion with Emery about his example from above that uses a script of mine, here's some insight I would provide that point toward the non-visual focus. 

This project is now going out for publication. At this point, it would be great if the provenance could do my job for me, which is pulling together the disparate pieces of inputs and essential details for sharing and archiving my entire workflow from data to publication. Something on the tack toward continuous integration. 

So, I guess Emery's mock-up seems to me to be pointing in the direction of output that would be making my process of gaining insights into my project workflow easier/automated in some way.

**Comment by MKLau** [comment]
See the #provtools channel on Slack.

**Comment by erboose** [comment]
[sensitivity-ddg-short.txt](https://github.com/End-to-end-provenance/dev/files/1078185/sensitivity-ddg-short.txt)
Here's a distilled DDG from Matt's sensitivity.R script, showing the random number seed value, values generated by functions that use the seed value, and output files.  Rerunning the script with the same seed value generates output files with the same hash values, as expected.

**Comment by erboose** [comment]
[basicTest-ddg-summary.txt](https://github.com/End-to-end-provenance/dev/files/1092056/basicTest-ddg-summary.txt)
Here's a DDG summary from basicTest.R (one of the regression tests) in a more readable format.
