### ISSUE TITLE
Vagrant image and default tools/script/data?

### ISSUE THREAD

**Issue by tfjmp** [End-to-end-provenance/dev#16]
I have provided a vagrant script (https://www.vagrantup.com/) to build a VM image containing a standard installation of RDataTracker for among other thing demo purpose and generally to provide a quick start.

However the image is quite bare bone at the moment (R and the minimum packages are installed). Is there any other tools that should be installed? Is there some demo script/data that we could provide?

Any suggestion more than welcome.

**Comment by MKLau** [comment]
Probably the ddg explorer as well. https://github.com/blernermhc/ddg

Double check with Barbara. The stable version has been hosted via Dropbox in the past

**Comment by tfjmp** [comment]
Ok. I will look at adding DDG to the image..

**Comment by tfjmp** [comment]
There is quite a lot of dependencies issue, there is some I started to fix, but there is some files that are missing and I assume present on the dropbox. 

Would it be possible to either 1) give me access to the dropbox so I can retrieve the needed dependencies; 2) add the dependencies to the ddg git repo and make sure it can build from the ant file (i.e. build xml).

What is missing at the moment are dependency on "Juliette" (I assumed R/Java interface library, but could not find where to get the source).

I am building prejure from source (i.e. https://github.com/prefuse/Prefuse), I assumed the head version would be alright. Let me know if we have dependency to a specific version.

**Comment by blernermhc** [comment]
Hi Thomas,

   You should not need any of the juliette stuff.  That is just for the 
jrunner target in the build file, which we are not using.

   I have created a folder in Dropbox under DDGExplorer / 
IncludedJarFiles where I have placed the jars that get linked into DDG 
Explorer.

   If you send me your email address, I can add you to the dropbox.

Barb

> Thomas Pasquier mailto:notifications@github.com
> May 23, 2016 at 12:32 PM
> 
> There is quite a lot of dependencies issue, there is some I started to 
> fix, but there is some files that are missing and I assume present on 
> the dropbox.
> 
> Would it be possible to either 1) give me access to the dropbox so I 
> can retrieve the needed dependencies; 2) add the dependencies to the 
> ddg git repo and make sure it can build from the ant file (i.e. build 
> xml).
> 
> What is missing at the moment are dependency on "Juliette" (I assumed 
> R/Java interface library, but could not find where to get the source).
> 
> I am building prejure from source (i.e. 
> https://github.com/prefuse/Prefuse), I assumed the head version would 
> be alright. Let me know if we have dependency to a specific version.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> https://github.com/End-to-end-provenance/dev/issues/16#issuecomment-221024626
> 
> Thomas Pasquier mailto:notifications@github.com
> May 21, 2016 at 5:51 AM
> 
> I have provided a vagrant script (https://www.vagrantup.com/) to build 
> a VM image containing a standard installation of RDataTracker for 
> among other thing demo purpose and generally to provide a quick start.
> 
> However the image is quite bare bone at the moment (R and the minimum 
> packages are installed). Is there any other tools that should be 
> installed? Is there some demo script/data that we could provide?
> 
> Any suggestion more than welcome.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> https://github.com/End-to-end-provenance/dev/issues/16

## 

http://www.getpostbox.comBarbara Lerner
Associate Professor and Chair
Computer Science Department
Mount Holyoke College

http://www.getpostbox.comhttp://www.getpostbox.com

**Comment by tfjmp** [comment]
thomas.francis.pasquier@gmail.com

**Comment by tfjmp** [comment]
Ok, got things to work, imported into an IDE and built there. The build.xml file on the ddg git repository need to be redone if we want a third party to be able to build ddg.

I will look at adding example data and source with some explanation from the document you sent me Barbara, thanks a lot :).

**Comment by tfjmp** [comment]
build.xml was fixed by Rahman, ubuntu version updated, jdk version as well, so all good there.

What is needed now:
- someone familiar with R workflow to list needed tools/libaries that are missing;
- if DDG comes packed with RDataTracker, make sure the package can build from sources (i.e. devtools:install_github works);
- identify datasets and scripts we want to use (put them in a repository? write a script that gather them from their original sources?)

Anything else that need to be done?
