### ISSUE TITLE
Brainstorm outreach possibilities

### ISSUE THREAD

**Issue by MKLau** [End-to-end-provenance/dev#20]

**Comment by MKLau** [comment]
From Aaron's twitter feed:

@_MKLau_ #RDataTracker project needs hash-tag & twitter feed; link up with #dagstuhleas participants? @owlice #rstats #opensource

**Comment by tfjmp** [comment]
I just had a though, do we want to have a presence on [ResearchGate](https://www.researchgate.net)?

**Comment by MKLau** [comment]
Hello,

Following our initial and very gratifying Shiny Developer Conference this past January, which sold out in a few days, RStudio is very excited to announce a new and bigger conference today!

rstudio::conf, the conference about all things R and RStudio, will take place January 13 and 14, 2017 in Orlando, Florida. The conference will feature talks and tutorials from popular RStudio data scientists and developers like Hadley Wickham, Yihui Xie, Joe Cheng, Winston Chang, Garrett Grolemund, and J.J. Allaire, along with lightning talks from RStudio partners and customers.

Preceding the conference, on January 11 and 12, RStudio will offer two days of optional training. Training attendees can choose from Hadley Wickham’s Master R training, a new Intermediate Shiny workshop from Shiny creator Joe Cheng or a new workshop from Garrett Grolemund that is based on his soon-to-be-published book with Hadley: Introduction to Data Science with R.

rstudio::conf is for R and RStudio users who want to learn how to write better shiny applications in a better way, explore all the new capabilities of the R Markdown authoring framework, apply R to big data and work effectively with Spark, understand the RStudio toolchain for data science with R, discover best practices and tips for coding with RStudio, and investigate enterprise scale development and deployment practices and tools, including the new RStudio Connect.

Not to be missed, RStudio has also reserved Universal Studio’s The Wizarding World of Harry Potter on Friday night, January 13, for the exclusive use of conference attendees!

Conference attendance is limited to 400. Training is limited to 70 students for each of the three 2-day workshops. All seats are are available on a first-come, first-serve basis.

Please go to http://www.rstudio.com/conference to purchase.

We hope to see you in Florida at rstudio::conf 2017!

For questions or issues registering, please email conf@rstudio.com. To ask about sponsorship opportunities contact anne@rstudio.com.

This email was sent to mkl48@nau.edu. If you no longer wish to receive these emails you may unsubscribe at any time.

**Comment by blernermhc** [comment]
That sounds great!  We should definitely have a presence there.

Barb

> MKLau mailto:notifications@github.com
> July 1, 2016 at 9:57 AM
> 
> Hello,
> 
> Following our initial and very gratifying Shiny Developer Conference 
> this past January, which sold out in a few days, RStudio is very 
> excited to announce a new and bigger conference today!
> 
> rstudio::conf, the conference about all things R and RStudio, will 
> take place January 13 and 14, 2017 in Orlando, Florida. The conference 
> will feature talks and tutorials from popular RStudio data scientists 
> and developers like Hadley Wickham, Yihui Xie, Joe Cheng, Winston 
> Chang, Garrett Grolemund, and J.J. Allaire, along with lightning talks 
> from RStudio partners and customers.
> 
> Preceding the conference, on January 11 and 12, RStudio will offer two 
> days of optional training. Training attendees can choose from Hadley 
> Wickham’s Master R training, a new Intermediate Shiny workshop from 
> Shiny creator Joe Cheng or a new workshop from Garrett Grolemund that 
> is based on his soon-to-be-published book with Hadley: Introduction to 
> Data Science with R.
> 
> rstudio::conf is for R and RStudio users who want to learn how to 
> write better shiny applications in a better way, explore all the new 
> capabilities of the R Markdown authoring framework, apply R to big 
> data and work effectively with Spark, understand the RStudio toolchain 
> for data science with R, discover best practices and tips for coding 
> with RStudio, and investigate enterprise scale development and 
> deployment practices and tools, including the new RStudio Connect.
> 
> Not to be missed, RStudio has also reserved Universal Studio’s The 
> Wizarding World of Harry Potter on Friday night, January 13, for the 
> exclusive use of conference attendees!
> 
> Conference attendance is limited to 400. Training is limited to 70 
> students for each of the three 2-day workshops. All seats are are 
> available on a first-come, first-serve basis.
> 
> Please go to http://www.rstudio.com/conference to purchase.
> 
> We hope to see you in Florida at rstudio::conf 2017!
> 
> For questions or issues registering, please email conf@rstudio.com 
> mailto:conf@rstudio.com. To ask about sponsorship opportunities 
> contact anne@rstudio.com mailto:anne@rstudio.com.
> 
> This email was sent to mkl48@nau.edu mailto:mkl48@nau.edu. If you no 
> longer wish to receive these emails you may unsubscribe at any time.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub 
> https://github.com/End-to-end-provenance/dev/issues/20#issuecomment-229953682, 
> or mute the thread 
> https://github.com/notifications/unsubscribe/AFLadtML8AyLoaeAZb8VBONZ88s2GZH0ks5qRRy3gaJpZM4Ir9yP.
> 
> MKLau mailto:notifications@github.com
> June 1, 2016 at 4:52 PM
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub 
> https://github.com/End-to-end-provenance/dev/issues/20, or mute the 
> thread 
> https://github.com/notifications/unsubscribe/AFLadjXp18PEBmEPsQnEM16WTfkpPM3fks5qHfEdgaJpZM4Ir9yP.

## 

http://www.getpostbox.comBarbara Lerner
Associate Professor
Computer Science Department
Mount Holyoke College

http://www.getpostbox.comhttp://www.getpostbox.com

**Comment by MKLau** [comment]
@tfjmp 

I like the idea of researchgate. I did a bit of looking for how to setup an "organization" account, but couldn't find anything. Do you know how we'd go about setting one up and how we might structure it?

**Comment by tfjmp** [comment]
You need to create a project and invite the members.

**Comment by MKLau** [comment]
Great! I just added this to the outreach channel on slack.

On Jul 1, 2016, at 10:03 AM, blernermhc <notifications@github.com<mailto:notifications@github.com>> wrote:

That sounds great! We should definitely have a presence there.

Barb

> MKLau mailto:notifications@github.com
> July 1, 2016 at 9:57 AM
> 
> Hello,
> 
> Following our initial and very gratifying Shiny Developer Conference
> this past January, which sold out in a few days, RStudio is very
> excited to announce a new and bigger conference today!
> 
> rstudio::conf, the conference about all things R and RStudio, will
> take place January 13 and 14, 2017 in Orlando, Florida. The conference
> will feature talks and tutorials from popular RStudio data scientists
> and developers like Hadley Wickham, Yihui Xie, Joe Cheng, Winston
> Chang, Garrett Grolemund, and J.J. Allaire, along with lightning talks
> from RStudio partners and customers.
> 
> Preceding the conference, on January 11 and 12, RStudio will offer two
> days of optional training. Training attendees can choose from Hadley
> Wickham’s Master R training, a new Intermediate Shiny workshop from
> Shiny creator Joe Cheng or a new workshop from Garrett Grolemund that
> is based on his soon-to-be-published book with Hadley: Introduction to
> Data Science with R.
> 
> rstudio::conf is for R and RStudio users who want to learn how to
> write better shiny applications in a better way, explore all the new
> capabilities of the R Markdown authoring framework, apply R to big
> data and work effectively with Spark, understand the RStudio toolchain
> for data science with R, discover best practices and tips for coding
> with RStudio, and investigate enterprise scale development and
> deployment practices and tools, including the new RStudio Connect.
> 
> Not to be missed, RStudio has also reserved Universal Studio’s The
> Wizarding World of Harry Potter on Friday night, January 13, for the
> exclusive use of conference attendees!
> 
> Conference attendance is limited to 400. Training is limited to 70
> students for each of the three 2-day workshops. All seats are are
> available on a first-come, first-serve basis.
> 
> Please go to http://www.rstudio.com/conference to purchase.
> 
> We hope to see you in Florida at rstudio::conf 2017!
> 
> For questions or issues registering, please email conf@rstudio.commailto:conf@rstudio.com
> mailto:conf@rstudio.com. To ask about sponsorship opportunities
> contact anne@rstudio.commailto:anne@rstudio.com mailto:anne@rstudio.com.
> 
> This email was sent to mkl48@nau.edumailto:mkl48@nau.edu mailto:mkl48@nau.edu. If you no
> longer wish to receive these emails you may unsubscribe at any time.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/End-to-end-provenance/dev/issues/20#issuecomment-229953682,
> or mute the thread
> https://github.com/notifications/unsubscribe/AFLadtML8AyLoaeAZb8VBONZ88s2GZH0ks5qRRy3gaJpZM4Ir9yP.
> 
> MKLau mailto:notifications@github.com
> June 1, 2016 at 4:52 PM
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/End-to-end-provenance/dev/issues/20, or mute the
> thread
> https://github.com/notifications/unsubscribe/AFLadjXp18PEBmEPsQnEM16WTfkpPM3fks5qHfEdgaJpZM4Ir9yP.

## 

http://www.getpostbox.comBarbara Lerner
Associate Professor
Computer Science Department
Mount Holyoke College

http://www.getpostbox.comhttp://www.getpostbox.com

**Comment by MKLau** [comment]
@tfjmp

Ok, just created a new project and added you.

On Jul 1, 2016, at 10:06 AM, Thomas Pasquier <notifications@github.com<mailto:notifications@github.com>> wrote:

You need to create a project and invite the members.

**Comment by margoseltzer** [comment]
This sounds like an excellent event — I don’t know what our options would be for “a presence” as it seems that the program is more well-established technologies.  That said, it would be great for several of us to go.

I’m definitely up for it — who else wants to attend?
- M

**Comment by blernermhc** [comment]
I am interested in attending.

Barb

> margoseltzer mailto:notifications@github.com
> July 1, 2016 at 11:26 AM
> This sounds like an excellent event — I don’t know what our options 
> would be for “a presence” as it seems that the program is more 
> well-established technologies. That said, it would be great for 
> several of us to go.
> 
> I’m definitely up for it — who else wants to attend?
> - M
> 
> > On Jul 1, 2016, at 9:57 AM, MKLau notifications@github.com wrote:
> > 
> > Hello,
> > 
> > Following our initial and very gratifying Shiny Developer Conference 
> > this past January, which sold out in a few days, RStudio is very 
> > excited to announce a new and bigger conference today!
> > 
> > rstudio::conf, the conference about all things R and RStudio, will 
> > take place January 13 and 14, 2017 in Orlando, Florida. The conference 
> > will feature talks and tutorials from popular RStudio data scientists 
> > and developers like Hadley Wickham, Yihui Xie, Joe Cheng, Winston 
> > Chang, Garrett Grolemund, and J.J. Allaire, along with lightning talks 
> > from RStudio partners and customers.
> > 
> > Preceding the conference, on January 11 and 12, RStudio will offer 
> > two days of optional training. Training attendees can choose from 
> > Hadley Wickham’s Master R training, a new Intermediate Shiny workshop 
> > from Shiny creator Joe Cheng or a new workshop from Garrett Grolemund 
> > that is based on his soon-to-be-published book with Hadley: 
> > Introduction to Data Science with R.
> > 
> > rstudio::conf is for R and RStudio users who want to learn how to 
> > write better shiny applications in a better way, explore all the new 
> > capabilities of the R Markdown authoring framework, apply R to big 
> > data and work effectively with Spark, understand the RStudio toolchain 
> > for data science with R, discover best practices and tips for coding 
> > with RStudio, and investigate enterprise scale development and 
> > deployment practices and tools, including the new RStudio Connect.
> > 
> > Not to be missed, RStudio has also reserved Universal Studio’s The 
> > Wizarding World of Harry Potter on Friday night, January 13, for the 
> > exclusive use of conference attendees!
> > 
> > Conference attendance is limited to 400. Training is limited to 70 
> > students for each of the three 2-day workshops. All seats are are 
> > available on a first-come, first-serve basis.
> > 
> > Please go to http://www.rstudio.com/conference to purchase.
> > 
> > We hope to see you in Florida at rstudio::conf 2017!
> > 
> > For questions or issues registering, please email conf@rstudio.com. 
> > To ask about sponsorship opportunities contact anne@rstudio.com.
> > 
> > This email was sent to mkl48@nau.edu. If you no longer wish to 
> > receive these emails you may unsubscribe at any time.
> > 
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly, view it on GitHub, or mute the thread.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub 
> https://github.com/End-to-end-provenance/dev/issues/20#issuecomment-229976078, 
> or mute the thread 
> https://github.com/notifications/unsubscribe/AFLadgtOmNYD7rv13NC1Lu8hXKurVFFjks5qRTG-gaJpZM4Ir9yP.
> 
> MKLau mailto:notifications@github.com
> June 1, 2016 at 4:52 PM
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub 
> https://github.com/End-to-end-provenance/dev/issues/20, or mute the 
> thread 
> https://github.com/notifications/unsubscribe/AFLadjXp18PEBmEPsQnEM16WTfkpPM3fks5qHfEdgaJpZM4Ir9yP.

## 

http://www.getpostbox.comBarbara Lerner
Associate Professor
Computer Science Department
Mount Holyoke College

http://www.getpostbox.comhttp://www.getpostbox.com

**Comment by tfjmp** [comment]
@MKLau I think at least Margo is also on research gate as well.
Another thing to do is looking at questions on Provenance and R, and answering.
I did not figure out yet, how you associate published paper to a project, but that should be the most basic feature, so it may be hidden somewhere in the interface.

**Comment by tfjmp** [comment]
@margoseltzer I am happy to attend if I am needed there.

**Comment by erboose** [comment]
I’m interested as well.

Emery

**Comment by margoseltzer** [comment]
Do you want to or would you prefer not to?
- M

**Comment by tfjmp** [comment]
@margoseltzer I think it may help understand what people are doing with R, and how they actually work so happy to be in.

**Comment by blernermhc** [comment]
It would be great for key technical people to meet Hadley WIckham.  He 
is running a workshop before the conference.

Barb

> Thomas Pasquier mailto:notifications@github.com
> July 1, 2016 at 11:54 AM
> 
> @margoseltzer https://github.com/margoseltzer I think it may help 
> understand what people are doing with R, and how they actually work so 
> happy to be in.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub 
> https://github.com/End-to-end-provenance/dev/issues/20#issuecomment-229982629, 
> or mute the thread 
> https://github.com/notifications/unsubscribe/AFLadgkzP54_f8BfuffCDu4nq3CSi1Swks5qRTghgaJpZM4Ir9yP.
> 
> MKLau mailto:notifications@github.com
> June 1, 2016 at 4:52 PM
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub 
> https://github.com/End-to-end-provenance/dev/issues/20, or mute the 
> thread 
> https://github.com/notifications/unsubscribe/AFLadjXp18PEBmEPsQnEM16WTfkpPM3fks5qHfEdgaJpZM4Ir9yP.

## 

http://www.getpostbox.comBarbara Lerner
Associate Professor
Computer Science Department
Mount Holyoke College

http://www.getpostbox.comhttp://www.getpostbox.com
