### ISSUE TITLE
Development Wiki

### ISSUE THREAD

**Issue by MKLau** [End-to-end-provenance/dev#21]
Questions from Thomas (slack #todiscuss)

Do we have plan for integration test? i.e. checking that all packages are still friendly with each others?

Rename beta to develop or dev? "Also dev branch should probably not be called beta. Beta should be release/tag on the fix or dev branches (e.g 1.2.3b)."

http://nvie.com/posts/a-successful-git-branching-model/
![](http://nvie.com/img/git-model@2x.png)

**Comment by MKLau** [comment]
https://github.com/blog/2019-how-to-undo-almost-anything-with-git

https://gist.github.com/lttlrck/9628955

http://blog.changecong.com/2012/10/rename-a-remote-branch-on-github/

https://github.com/stephencelis/ghi

**Comment by MKLau** [comment]
1. Clone
2. Branch 
3. Work on branch and push to github 
4. Checks 
5. Pull request
6. Review 
7. Merge onto development 
8. Check and test 
9. Merge onto master 
10. Tag and announce

**Comment by tfjmp** [comment]
@MKLau My  question have more to do with making sure RDataTracker, DDGExplorer (and in the future more) are still working consistently together. Making sure that if/when dependencies version is updated it works well with everything else (for example Ubuntu 14.04 Vagrant was not too friendly with Java 8, to be more precise openjdk-8).

My point is that we need to define more formally the "check and test", and ideally automate most of it (writing scripts and using tools such as Jenkins[1]).

[1] https://jenkins.io/

**Comment by MKLau** [comment]
@tfjmp I definitely see your point. I think that this is worth spending time on given that things will get even more complicated as we start to integrate with CPL. 

Do you know how to use Jenkins?

**Comment by tfjmp** [comment]
@MKLau no but one can learn. We could take some time to look at this on the week of the 4th. What do you think? Would probably be easier offline.

**Comment by MKLau** [comment]
Adding SCRUM/Huboard!
