### ISSUE TITLE
DDGexplorer: Simplify install process

### ISSUE THREAD

**Issue by MKLau** [End-to-end-provenance/dev#24]

**Comment by rahmanhafeezul** [comment]
I could write all of the installation instructions into one single shell script, say 'run.sh'
The user would then have to just install it with: $ ./run.sh 
The instruction 'java -jar ddg-explorer.jar' will then start the DDGExplorer.

**Comment by MKLau** [comment]
Thanks, good thought, that's definitely simpler. 

I'm also thinking of the typical ecologist R user. If she were going to use the DDG Explorer, what would the expected process be? I'm thinking that this is someone that uses R regularly, but would like to also use DDG explorer to visualize a script, but not necessarily someone that works from the command line regularly. 

Is it possible to make the sh script executable via clicking on the script?

Also, would this also work Windows machines?

**Comment by rahmanhafeezul** [comment]
For a general user, he would just download the 'ddg-explorer.jar', either from the website or from github and just double click it to visualize his Data Derivation Graphs.

For someone who is contributing to the codebase of DDGExplorer, he will have to build/compile the src code after modifying the code and for him, the commands for building the code will be present in 'run.sh' shell script.

It ideally would work on any machine that has Java enabled. So, it should work on Windows as well. Will try and check it though..

**Comment by tfjmp** [comment]
Naive question, but why do we need a shell script? There is the build.xml file (now properly working, thanks!). Isn't that enough?

**Comment by MKLau** [comment]
I actually don't have experience using xml but sounds like the build.xml is probably good/sufficient for developers. 

My initial thought for this thread was about expanding the user community. It would be great to have the tools in a format that a typical scientist (not a data, computational and/or CS specialist) would be familiar with. I started wondering this when Thomas setup the virtual machine and came back to it when my student was struggling with the DDG explorer install. 

Most users are probably expecting some kind of clickable installation program that they can run, e.g. a disk mount that runs the install (.dmg). Could we do something like that?

**Comment by blernermhc** [comment]
For DDG Explorer, we can make available a jar file that is itself 
double-clickable, no installation required.

Barb

> MKLau mailto:notifications@github.com
> June 20, 2016 at 11:12 AM
> 
> I actually don't have experience using xml but sounds like the 
> build.xml is probably good/sufficient for developers.
> 
> My initial thought for this thread was about expanding the user 
> community. It would be great to have the tools in a format that a 
> typical scientist (not a data, computational and/or CS specialist) 
> would be familiar with. I started wondering this when Thomas setup the 
> virtual machine and came back to it when my student was struggling 
> with the DDG explorer install.
> 
> Most users are probably expecting some kind of clickable installation 
> program that they can run, e.g. a disk mount that runs the install 
> (.dmg). Could we do something like that?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub 
> https://github.com/End-to-end-provenance/dev/issues/24#issuecomment-227171991, 
> or mute the thread 
> https://github.com/notifications/unsubscribe/AFLadiMsdWjQ5_9hMI6HG0f_cz_1rIKsks5qNq3VgaJpZM4I2drJ.
> 
> MKLau mailto:notifications@github.com
> June 15, 2016 at 11:10 AM
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub 
> https://github.com/End-to-end-provenance/dev/issues/24, or mute the 
> thread 
> https://github.com/notifications/unsubscribe/AFLadurj7ZWT_GZgQHEtuqg8BouvWhacks5qMBXtgaJpZM4I2drJ.

## 

http://www.getpostbox.comBarbara Lerner
Associate Professor and Chair
Computer Science Department
Mount Holyoke College

http://www.getpostbox.comhttp://www.getpostbox.com

**Comment by tfjmp** [comment]
To build it java project, it is litteraly just:
$ ant <target> # need to check in the build.xml file or in the doc what is the target you want
If the build.xml is done correctly it build like a charm.

For distributing, did you try to get your student to use the vagrant VM thing, by any chance? 

I am really curious what is the usual environment of scientist and their normal workflow.  I am happy to spend time with you/them once in Harvard to look at this.

We could also build an installer (automating the process when new releases are pushed ideally). The problem is that things will probably be easy for Unix-based systems, and a bit more complicated once moving away from this.

**Comment by MKLau** [comment]
No I didn't have her use the Vagrant thing you created. I thought that it was a virtual machine for use to do demos for courses. Let me try it out myself and then I'll pass it along to her. She's on a Mac, so shouldn't be any OS compatibility issues.
