### ISSUE TITLE
Scrum task board: tracking task completion and who does what.

### ISSUE THREAD

**Issue by tfjmp** [End-to-end-provenance/dev#27]
You may have heard of scrum task board it looks something like this:
![Scrum task board](http://cdn.slidehunter.com/wp-content/uploads/scrum-task-board-template-powerpoint.jpg)

It would allow to track who is doing what and what needs to be done relatively easily. All wanted features are added to the "stories" column.

Once clear with the requirements of a given feature, they can be moved to the "ready" column where they will wait for assignment. (Here someone is needed to keep the "stories" clean, and make sure they progress to a ready state depending on their priority). Stories should be assigned to millestone (e.g. release number once it becomes clear).

People pick stories from the ready column and assign it to themselves. Once they start working on it they move it to the "In Progress" column. Once the task is completed it can be moved to the "Testing" column where the person responsible for merge/review on the project do his/her job (he should therefore be assigned to the task). From there the story either goes to "Done" or back to "Ready" with comments on what went wrong or what more is needed.

The good news is that there is tools for this to integrate nicely with github. I created an example on another project I work on, it looks like this:
https://huboard.com/CamFlow/camflow-dev
https://huboard.com/CamFlow/camflow-dev#/milestones

The "stories" appear as issues on github:
https://github.com/CamFlow/camflow-dev/issues

What do people think? I am happy to have a try at this with DDG-Explorer if I have the green light, then once we are comfortable with the tool extend to the other packages.

**Comment by blernermhc** [comment]
Does the integration go in both directions, so that if somebody posts an issue in github, does it get picked up by HuBoard as a story?

Have you looked at waffle.io?  Seems to have similar functionality.  I am not familiar with either of these tools.

**Comment by MKLau** [comment]
Yeah, huboard has access to github, so it keeps both the board and github in sync.

Just looked at waffle, and it looks great. Similar functionality to huboard. Waffle's interface on iOS is actually readable, unlike huboard. I'm not 100% sure, but we should be able to use either one of them simultaneously. 

I'll try waffle some more and see.

**Comment by tfjmp** [comment]
I am pretty keen to go with either of those tools. Should we decide which one to use and make it active on all repositories?

**Comment by MKLau** [comment]
Yeah, I think so. It depends on the system that waffle uses. Huboard co-opts the issue labeling to organize issues in its interface.

On Jun 28, 2016, at 4:39 PM, Thomas Pasquier <notifications@github.com<mailto:notifications@github.com>> wrote:

I am pretty keen to go with either of those tools. Should we decide which one to use and make it active on all repositories?

**Comment by tfjmp** [comment]
Ok so installed wafle there on an other project:
https://waffle.io/tfjmp/php2uni
https://github.com/tfjmp/php2uni/issues

From the github side of things the way they work seems exactly identical. 

One thing missing from Waffle is the milestone view (allows to see what needs to be done for release X, if that's how we plan to use milestone). If being able to have the thing presented nicely on smartphone is a big issue we could go with Waffle, otherwise stick with huboard?

**Comment by blernermhc** [comment]
I'm game to try one of these.  Milestones seems more important to me 
than a smartphone interface.

Barb

> Thomas Pasquier mailto:notifications@github.com
> June 28, 2016 at 5:10 PM
> 
> Ok so installed wafle there on an other project:
> https://waffle.io/tfjmp/php2uni
> https://github.com/tfjmp/php2uni/issues
> 
> From the github side of things the way they work seems exactly identical.
> 
> One thing missing from Waffle is the milestone view (allow to see what 
> needs to be done for X release if that's how we plan to use 
> milestone). If being able to have the thing presented nicely on 
> smartphone is a big issue we could go with Waffle, otherwise stick 
> with huboard?
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub 
> https://github.com/End-to-end-provenance/dev/issues/27#issuecomment-229184662, 
> or mute the thread 
> https://github.com/notifications/unsubscribe/AFLadqG5kdUCcR6yyBbi1lDgA_plDs1bks5qQY26gaJpZM4I7dJO.
> 
> Thomas Pasquier mailto:notifications@github.com
> June 22, 2016 at 2:46 AM
> 
> You may have heard of scrum task board it looks something like this:
> Scrum task board 
> https://camo.githubusercontent.com/53577ca19c6f259081a5b6d8d3132c918623f44c/687474703a2f2f63646e2e736c69646568756e7465722e636f6d2f77702d636f6e74656e742f75706c6f6164732f736372756d2d7461736b2d626f6172642d74656d706c6174652d706f776572706f696e742e6a7067
> 
> It would allow to track who is doing what and what needs to be done 
> relatively easily. All wanted features are added to the "stories" column.
> 
> Once clear with the requirements of a given feature, they can be moved 
> to the "ready" column where they will wait for assignment. (Here 
> someone is needed to keep the "stories" clean, and make sure they 
> progress to a ready state depending on their priority). Stories should 
> be assigned to millestone (e.g. release number once it becomes clear).
> 
> People pick stories from the ready column and assign it to themselves. 
> Once they start working on it they move it to the "In Progress" 
> column. Once the task is completed it can be moved to the "Testing" 
> column where the person responsible for merge/review on the project do 
> his/her job (he should therefore be assigned to the task). From there 
> the story either goes to "Done" or back to "Ready" with comments on 
> what went wrong or what more is needed.
> 
> The good news is that there is tools for this to integrate nicely with 
> github. I created an example on another project I work on, it looks 
> like this:
> https://huboard.com/CamFlow/camflow-dev
> https://huboard.com/CamFlow/camflow-dev#/milestones
> 
> The "stories" appear as issues on github:
> https://github.com/CamFlow/camflow-dev/issues
> 
> What do people think? I am happy to have a try at this with 
> DDG-Explorer if I have the green light, then once we are comfortable 
> with the tool extend to the other packages.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub 
> https://github.com/End-to-end-provenance/dev/issues/27, or mute the 
> thread 
> https://github.com/notifications/unsubscribe/AFLadvJvx6KzcT2EVDOD8hyZbC07ixTcks5qONpSgaJpZM4I7dJO.

## 

http://www.getpostbox.comBarbara Lerner
Associate Professor and Chair
Computer Science Department
Mount Holyoke College

http://www.getpostbox.comhttp://www.getpostbox.com

**Comment by tfjmp** [comment]
Oki, it should be setup, please have a look there:
https://huboard.com/End-to-end-provenance

Move the task in progress where they belong and assign them. That should also helps in Tuesdays meetings.
