### ISSUE TITLE
Advertise July 12th tutorial on twitter&researchgate?

### ISSUE THREAD

**Issue by tfjmp** [End-to-end-provenance/dev#29]

**Comment by MKLau** [comment]
Already up on Twitter. I'll keep posting through the weekend and week.

On Jul 1, 2016, at 7:32 PM, Thomas Pasquier <notifications@github.com<mailto:notifications@github.com>> wrote:

Assigned #29https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_End-2Dto-2Dend-2Dprovenance_dev_issues_29&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=yYM9bdhQa7fj0pqtCBPxMvjOe6gKXC-k_OhnGcaB0ZI&m=M7W6ZvjhQu4qFUZnJF9jc999U143nLYWcQBEqWtIKnE&s=i2cY6cLDDYWH41bPgu-WQAr6IwAZzndRCJM_aExmv6A&e= to @MKLauhttps://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_MKLau&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=yYM9bdhQa7fj0pqtCBPxMvjOe6gKXC-k_OhnGcaB0ZI&m=M7W6ZvjhQu4qFUZnJF9jc999U143nLYWcQBEqWtIKnE&s=7sKgkaozyG5KrIjW1NCAsClGXoua2eXlk6p4zf4Hyyk&e=.

##
