### ISSUE TITLE
Get camflow running on Odyssey

### ISSUE THREAD

**Issue by MKLau** [End-to-end-provenance/dev#32]

**Comment by tfjmp** [comment]
What's odyssey?

**Comment by margoseltzer** [comment]
The research computing cluster at Harvard
- M

**Comment by MKLau** [comment]
https://rc.fas.harvard.edu/odyssey-infographic/

**Comment by tfjmp** [comment]
Thanks both. Lets discuss that next time you are around Matt?

**Comment by MKLau** [comment]
Sounds good. I’m at HF until Thursday morning.

On Aug 30, 2016, at 3:21 PM, Thomas Pasquier <notifications@github.com<mailto:notifications@github.com>> wrote:

Thanks both. Lets discuss that next time you are around Matt?

**Comment by MKLau** [comment]
Looks like Camflow is not the way to go to get a real time view of DDG, given that it's still in Beta and that the admins probably won't go for a process accessing the kernel. So, we're looking into getting RDataTracker to actually incrementally build the DDG as the process is running. This would be useful for both the purpose of viewing the DDG in real time and reducing the memory demand. 

Closing this issue here, but see 

https://github.com/End-to-end-provenance/RDataTracker/issues/154#issuecomment-244465549
