### ISSUE TITLE
Should we re-structure the JSON format to allow incremental building?

### ISSUE THREAD

**Issue by MKLau** [End-to-end-provenance/dev#4]

**Comment by margoseltzer** [comment]
Rahman and I have been looking at the JSON quite carefully now because he is starting to build a static viewer in R (as a first step towards a native R DDG Explorer).  I think there are a few modifications that we are going to need to make (which we can discuss on Tuesday and then assign appropriately).
1. The current json is outputting files in the example namespace (e.g., the prefix ex is bound to the example.org domain and all our names are prefixed with ex:).  I can imagine either:

binding prefix (ex) to a URL we own and leaving everything else unchanged or binding a better prefix (e.g., rdt) to a URL we own and using that.
1. It appears that the process edges are inferred as going from p1->p2->p3 -- they are not represented explicitly, but I think we probably want them to be real edges (although there is not necessarily an obvious edge type -- I"m reading the standard to figure out).
2. The data flow edges are all embedded in structures by type which will make incremental construction impossible.  I think we just want to raise them up a level in the JSON.

**Comment by erboose** [comment]
Glad someone is looking at this!  I wrote the code to generate the JSON file but had little to go on and trouble finding a validator that worked. This should be straightforward if we had a specific example of exactly what the JSON file should look like.

**Comment by margoseltzer** [comment]
Looking into this a bit more.  I think that the control flow edges should be described as wasInformedBy.

So, let's say we have the following in ddg.txt:

Operation p2 "2-data(mtcars) [1]" Value="data(mtcars)" Time="0.0299999999999998";
CF p1 p2
Operation p3 "3-cars.df <- mtcars [2]" Value="cars.df <- mtcars" Time="0.0389999999999997";
CF p2 p3
Snapshot d1 "1-cars.df" Value="/Users/margo/Research/prov-project/src/ddg/1-cars.df.csv" Time="2016-04-27T12.11.02EDT";
DF p3 d1
Start p4 "4-Process 4 cylinder cars [6]" Value="Process 4 cylinder cars" Time="0.069";
CF p3 p4

I think that should look like the following in PROV JSON:

"activity" : {
   "p2" : {
        "value":"data(mtcars)",
        "time":"0.029998",
        "line":"1"
    }
}

"wasInformedBy" : {
    "e1" : {
        "prov:informant": "p1",
        "prov:informed": "p2"
}

"activity" : {
   "p3" : {
        "value":"cars.df <- mtcars",
        "time":"0.038999",
        "line":"2"
    }
}

"wasInformedBy" : {
    "e2" : {
        "prov:informant": "p2",
        "prov:informed": "p3"
}

"entity" : {
    "d1" : {
        "name" : "cars.df",
        "value" : "/Users/margo/Research/prov-project/src/ddg/1-cars.df.csv"
    }
}

"wasGeneratedBy" : {
    "e3" : {
        "prov:entity" : "d1",
        "prov:activity" : "p3",
        "prov:time" : "2016-04-27T12.11.02EDT"
    }
}

where I'm using p's for activity nodes (process nodes in ddg terminology)
d's for data nodes
e's for edge objects (relationships in PROV terminology)

**Comment by erboose** [comment]
Note that the JSON file is currently built from the data node, procedure node, and data flow tables (data frames) after the script completes execution.  If we want to create a tool in R to visualize the DDG as the script is executing, it might be simplest to get the necessary information directly from these tables.

**Comment by tfjmp** [comment]
Should we also aim at supporting PROV-N format directly?

e.g. https://provenance.ecs.soton.ac.uk/store/documents/114419/

Frome the spec (i.e. https://www.w3.org/Submission/2013/SUBM-prov-json-20130424/) the PROV-N format seems more compact.

**Comment by tfjmp** [comment]
There is an issue with the current format. Following JSON specification:

```
An object structure is represented as a pair of curly brackets
   surrounding zero or more name/value pairs (or members).  A name is a
   string.  A single colon comes after each name, separating the name
   from the value.  A single comma separates a value from a following
   name.  <b>The names within an object SHOULD be unique</b>.
```

However, the current .json created by RDataTracker contains many duplicate.

The file currently being generated won't necessarily be supported by all JSON parser (and is not).

There is also an extra ',' at the end.

Practically that means that all activities, entities etc... (as well as edges of the same type) need to be grouped together.

**Comment by tfjmp** [comment]
In wasGeneratedBy: activity and entity are reversed.

**Comment by tfjmp** [comment]
I made change on my RDataTracker fork this morning in order to get correctly formatted JSON file. It goes through the parser and can be displayed! I will add comments and create a pull request, if people think that's the appropriate thing to do.

Probably should go to fix if everyone happy with it?

**Comment by blernermhc** [comment]
Sounds good to me.

Barb

> Thomas Pasquier mailto:notifications@github.com
> July 14, 2016 at 8:08 AM
> 
> I made change on my RDataTracker fork this morning in order to get 
> correctly formatted JSON file. It goes through the parser and can be 
> displayed! I will add comments and create a pull request, if people 
> think that's the appropriate thing to do.
> 
> Probably should go to fix if everyone happy with it?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub 
> https://github.com/End-to-end-provenance/dev/issues/4#issuecomment-232647418, 
> or mute the thread 
> https://github.com/notifications/unsubscribe/AFLadm5jV9olbU7ganN7Ty6cpqGgdp8xks5qVibIgaJpZM4IiVnp.
> 
> MKLau mailto:notifications@github.com
> May 19, 2016 at 10:48 AM
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> https://github.com/End-to-end-provenance/dev/issues/4

## 

http://www.getpostbox.comBarbara Lerner
Associate Professor
Computer Science Department
Mount Holyoke College

http://www.getpostbox.comhttp://www.getpostbox.com

**Comment by MKLau** [comment]
Closing this issue after reviewing this question at the Mt Holyoke meeting. Creating a set of issues in RDataTracker aimed at accomplishing the implementation of JSON and periodic/incremental writing of DDG.json.
