### ISSUE TITLE
Agenda for Nov17 meeting

### ISSUE THREAD

**Issue by MKLau** [End-to-end-provenance/dev#43]

**Comment by blernermhc** [comment]
I am most interested in learning more about CamView, specifically what features it currently has for viewing provenance and what features are being planned for it.

What are others interested in discussing?

**Comment by MKLau** [comment]
Hi Barb, that sounds good. In terms of scheduling, I would probably be coming from Cambridge with Thomas via I90, and could get out to Holyoke between 9 and 10 depending on traffic. Happy to stay until the afternoon/early evening. But it would be nice not to get back too late.

With regard to discussion, I also would like to go over the details of both visualizers and think big picture about what the team needs are in terms of our overall project goals and energy/time for development.

Also, it would be good to spend some time talking about target audience. Echoing Emory, I keep coming back to the thought of the database manager as a priority end-user.

**Comment by MKLau** [comment]
Shifting to RDataTracker issue system, see Nov Meeting Milestone.
