### ISSUE TITLE
Connect slack and github

### ISSUE THREAD

**Issue by MKLau** [End-to-end-provenance/dev#5]
https://github.com/integrations/slack

**Comment by tfjmp** [comment]
I have done that in the past, that's just a few click. Want me to do it?

**Comment by MKLau** [comment]
Margo said she would set it up, but if you've done it before, it would probably save time. @margoseltzer?

**Comment by tfjmp** [comment]
https://endtoendprovenance.slack.com

I sent invitation both to you and Margo, check if everything is ok before we invite everyone else.
