### ISSUE TITLE
What is the tibble data object?

### ISSUE THREAD

**Issue by MKLau** [End-to-end-provenance/dev#59]

**Comment by fong22e** [comment]
The way I understand it from the conference, it seems like the tibble data object is like a different take on data frames. Some talks in the conference really emphasised the fact that tibbles allow for easier usage and manipulation of list-columns, which is what I understood to be columns of lists.

These sites may be helpful:
[tidyverse/tibble - GitHub](https://github.com/tidyverse/tibble)
[tibble package on CRAN](https://cran.r-project.org/web/packages/tibble/index.html)
