### ISSUE TITLE
Create a wiki for organizing projects and workflow

### ISSUE THREAD

**Issue by MKLau** [End-to-end-provenance/dev#6]
https://github.com/End-to-end-provenance/dev/wiki/Start-Here!

https://github.com/End-to-end-provenance/dev/wiki

**Comment by MKLau** [comment]
Examples

https://en.wikipedia.org/wiki/GitHub
https://github.com/ParsePlatform/parse-server/wiki
https://github.com/oneclick/rubyinstaller/wiki/Development-Kit
http://www.dropboxwiki.com

**Comment by tfjmp** [comment]
Github come with wiki feature (fourth tab on a project page), are they not alright?

**Comment by MKLau** [comment]
Yep, I wanted to take a look at the structure of Dropbox's wiki to get an idea of how to organize content.

**Comment by MKLau** [comment]
Along this tack, do you have a good "github organization strategy" resource that you would suggest using? It would be great to not have to re-invent the wheel, but I've done a bit of googling and didn't come up with anything.

**Comment by tfjmp** [comment]
Ah not really, outside of working on branches/forks rather than on master ;). Although we found a private github repository for papers writing quite useful in the past.

**Comment by MKLau** [comment]
Yeah, me too. I'm hoping to make things as painless as possible for the others so that we'll actually use it.
