### ISSUE TITLE
Collect repos under End-to-end-provenance

### ISSUE THREAD

**Issue by MKLau** [End-to-end-provenance/dev#7]

**Comment by MKLau** [comment]
- RDatatracker
- DDGexplorer
- End-to-end

**Comment by tfjmp** [comment]
Either you own those repos and then you need to do the transfer into the management interface, if not you need to fork those and transfer the fork here (though fork are a bit more of a pain if the main repos are still in dev).

**Comment by MKLau** [comment]
Yeah, I think you're right, we want to transfer and not fork; otherwise, we have these weird branching, independent software lineages. But, we'll want to make sure that the various development teams are on board with bringing the repos together under one org.

**Comment by blernermhc** [comment]
RDataTracker and DDGExplorer have been transferred.
